export const ImagesAsset = {
    home: require('./home.png'),
    home_inactive: require('./home_inactive.png'),
    left_arrow: require('./left_arrow.png'),
    search: require('./search.png'),
    date: require('./date.png'),
    play: require('./play.png'),
    cinema_active: require('./cinema_active.png'),
    cinema: require('./cinema.png'),
    download: require('./download.png'),
    quality: require('./quality.png'),
    share: require('./share.png'),
    star: require('./star.png'),
    download_: require('./download_.png'),
    more: require('./more.png'),
    download_inactive: require('./download_inactive.png'),
    download_white: require('./download_white.png'),
    more_inactive: require('./more_inactive.png'),
    coming_soon: require('./coming_soon.png'),
    add: require('./add.png'),
}